#!/bin/sh
SHELL=/bin/bash
## スクリプト配置フォルダを指定する.
HOME=/opt/scripts
MAILTO=""

## 書式
## minute hour day mon dow   command

## 土曜 3:05 にシステムの再起動を試行.
5 3 * * sat  root $HOME/reboot_sys.sh

## エンコード投入
15 3 * * * root node $HOME/enqueue_enc.js

