version: "3.7"
services:
  mysql:
    image: mariadb:10.4
    volumes:
      - epg-mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: epgstation
      MYSQL_ROOT_PASSWORD: epgstation
      MYSQL_DATABASE: epgstation
      TZ: "Asia/Tokyo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --performance-schema=false --expire_logs_days=1
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

volumes:
  epg-mysql-db:
    driver: local
